print services requires accounts url (#240)
Fixes:
```
Error: Missing config for attributes: AccountsUrl
    at /usr/src/app/bundle.js:536360:11
    at Object.<anonymous> (/usr/src/app/bundle.js:536363:3)
    at Module._compile (node:internal/modules/cjs/loader:1562:14)
    at Object..js (node:internal/modules/cjs/loader:1699:10)
    at Module.load (node:internal/modules/cjs/loader:1313:32)
    at Function._load (node:internal/modules/cjs/loader:1123:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49
```

Signed-off-by: Antonio Cheong <acheong@duti.dev>